FROM maven:3.9.6-eclipse-temurin-21 AS build

WORKDIR /workspace
COPY ./api-estoque/crud/pom.xml .
RUN mvn dependency:go-offline -B

COPY ./api-estoque/crud/src ./src

RUN mvn package -DskipTests

FROM eclipse-temurin:21-jdk
WORKDIR /app

COPY --from=build /workspace/target/*.jar app.jar

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]