spring.application.name=crud
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false
security.jwt.secret-key=secret
security.jwt.expiration-time=86400000
spring.datasource.url=jdbc:postgresql://localhost:5433/estoque
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.redis.host=localhost
spring.redis.port=6379
spring.redis.timeout=5000ms
spring.redis.lettuce.pool.enabled=true
spring.redis.lettuce.pool.max-active=8
spring.redis.lettuce.pool.max-idle=8
spring.redis.lettuce.pool.min-idle=0